### PR TITLE
updates project to respect firebaseMessagingVersion 

### PR DESCRIPTION
**Pull request by bdirito**
@capacitor/push-messaging

### CODE REVIEW

**Comment by bdirito** [comment]
fixes #92

**Comment by bdirito** [comment]
@stewones - you mentioned you were looking to test this? do you need anything from me for that? 

Id prefer to use a 'real' release of the plugin in our project if possible.

**Comment by bipoza** [comment]
> @stewones - you mentioned you were looking to test this? do you need anything from me for that?
> 
> Id prefer to use a 'real' release of the plugin in our project if possible.

I have tested these changes on a migrated Capacitor 2 to 3 project and it works perfectly.
If you need it, I can upload a small demo to check that it works well.

If the changes don't break other functionalities, it would be nice to release this.
Thanks!

**Comment by stewones** [comment]
Thanks, it's patched
@capacitor-community/fcm@2.0.2

**Pull request merged**
