### PR TITLE
Update pod file to fix failing iOS builds

### PR DESCRIPTION
**Pull request by iOlivier**
This should solve this issue: https://github.com/capacitor-community/fcm/issues/67

### CODE REVIEW

**Comment by chvonrohr** [comment]
Thx that was fast 💯

**Comment by typeoneerror** [comment]
Fantastic, thanks @iOlivier. Anything I can do to help get this merged and released?

**Comment by denisLoncaric** [comment]
why not fixing to v7.11.0?

**Comment by iOlivier** [comment]
> Fantastic, thanks @iOlivier. Anything I can do to help get this merged and released?

Unfortunately, only the maintainers with write access can merge this PR. So we can only wait...

**Comment by iOlivier** [comment]
> why not fixing to v7.11.0?

Done ;)

**Comment by typeoneerror** [comment]
> Done ;)

Should probably update in the `PluginTests` target as well.

**Comment by aabanaag** [comment]
Is there any update for this?

**Comment by stewones** [comment]
Thanks, I will test and merge this weekend 👍

**Pull request merged**
