### PR TITLE
feat: update to Capacitor 6

### PR DESCRIPTION
**Pull request by chrisweight**
Uses `npx @capacitor/plugin-migration-v5-to-v6@latest` to update this plugin to Capacitor 6

### CODE REVIEW

**Comment by stewones** [comment]
Thanks @chrisweight I'll look into this asap

**Comment by WMOH-DEV** [comment]
@stewones  Any update ??

**Comment by stewones** [comment]
just released guys

thank you @chrisweight

**Comment by chrisweight** [comment]
No worries, cheers!

**Pull request merged**
